stages:
  - test
  - docker

pylint:
  stage: test
  image: python:alpine
  script:
    - pip install -r requirements.txt
    - pip install pylint
    - pylint start.py

shellcheck:
  stage: test
  image: ubuntu:bionic
  script:
    - apt-get -qq update
    - apt-get -qq -y install shellcheck
    - shellcheck entrypoint.sh

build-docker:
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  stage: docker
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME .
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME
